### PR TITLE
Chromia Integration

### PR DESCRIPTION
**Pull request by superoo7**
# Relates to:

Adding Chromia Chain supports into Goat SDK

# Background

Chromia is a Layer 1 built on top of PostgreSQL, which is useful for storing all kinds of onchain data. We have our own token standards call FT4 (similar to ERC20 & ERC721)

## What does this PR do?
- Integrate Chromia Wallet
- Add sendCHR tool function
- Add Chromia Demo in Vercel AI

## What kind of change is this?
Touching some part of @goat-sdk/core to implement sendCHR

# Documentation changes needed?

Probably need to add some official docs on the implementation, but i've done a README.md docs in @goat-sdk/wallet-chromia

# Testing

## For plugins
- [x] I have tested this change locally with key pair wallets
- [ ] I have tested this change locally with hosted wallets (e.g. Crossmint Smart Wallets, etc.)

### CODE REVIEW

**Review by 0xaguspunk — APPROVED** [review]
Three small comments:
1. Remove the changelog (not needed)
2. Could you run `pnpm change:add` before merging?
3. Could you add the wallet package to https://github.com/goat-sdk/goat/blob/main/goat.code-workspace

Nice work! We should coordinate an announcement for this one! :)

**Comment by superoo7** [comment]
Alright done @0xaguspunk, lmk know anything else, i'm still learning about monorepo, not used to this hahaa

**Comment by 0xaguspunk** [comment]
@superoo7 could you:
1. Delete the `pnpm-lock` file and run `pnpm i`
2. Run`pnpm lint:fix` and manually fix the issues it could not resolve
3. Commit and push again

**Comment by 0xaguspunk** [comment]
I'll merge and fix it.

**Pull request merged**
